FROM datahubproject/datahub:bio-notebook-base

ADD ./internal_README.MD $HOME/README.MD
RUN fix-permissions /home/$NB_USER

USER biodatahub

EXPOSE 8888
ENTRYPOINT ["tini", "-g", "--"]
CMD jupyter-lab --ip=0.0.0.0