FROM datahubproject/datahub:bio-notebook-base

ADD ./internal_README.MD $HOME/README.MD
RUN mkdir /home/biodatahub/private \
    && mkdir /home/biodatahub/public \
    && fix-permissions /home/$NB_USER

USER biodatahub
ENTRYPOINT ["tini", "-g", "--"]
CMD [ "jupyterhub-singleuser"]