FROM datahubproject/datahub:bio-notebook-base

ADD ./internal_README.MD $HOME/README.MD
RUN mkdir /home/biodatahub/private
RUN mkdir /home/biodatahub/public


RUN chown -R biodatahub:biodatahub $HOME

USER biodatahub

CMD [ "jupyterhub-singleuser"]